### ISSUE TITLE
Documentation Required

### ISSUE THREAD

**Issue by AnirbanKundu** [PredixDev/px-login#2]
Can we have more documentation for this control  ?

**Comment by randyaskin** [comment]
Closing due to age. See latest [API document](https://www.predix-ui.com/#/components/px-login/) for px-login and the [predix.io docs site](https://docs.predix.io/en-US/content/service/security/user_account_and_authentication/using-uaa-for-your-application-login#concept_b10de138-8e7f-48f8-9719-7f84214ed6d4) for more information on UAA.
