### ISSUE TITLE
Provide option for adjusting text color (custom style)

### ISSUE THREAD

**Issue by austinmcdaniel** [PredixDev/px-login#29]
Currently the text color is set to a very dark color (maybe black?), but this doesn't work well with a dark background color. It would be nice to have some custom style options to adjust the color of the icon and text.

## Environment:
px-login v2.0.6
Chrome 60.0.3112.113
Windows 7

![image](https://user-images.githubusercontent.com/16106173/30071550-b6d5fcba-922c-11e7-8150-6f7b7ffa5dba.png)

**Comment by randyaskin** [comment]
A few options, depending how your code is set up:
- use px-dark-theme instead of px-theme for the login component specifically, since you've placed it on a dark background - mixing themes is possible, but a bit tricky, so easier would be...
- use the actionable-text variables and scope them to the login component, e.g.
```
px-login {
  --px-actionable-alt-text-color: gray;
  --px-actionable-alt-text-color--hover: lightgray;
  --px-actionable-alt-text-color--active: lightgray;
}
```
We could expose new style variables specific to this component, but it would be duplicating code from actionable-text. But this and other questions on Slack today have our team talking about what our strategy should be for documenting these situations, so thanks for asking!

**Comment by austinmcdaniel** [comment]
Looks like the "--px-actionable" custom styles only apply to the px-popover component within the px-login component which doesn't really help since the popover works fine.

This would work if the div with the userName had the actionable class.

I'll have to try out the px-dark-theme.

**Comment by randyaskin** [comment]
Ah, my bad, I was looking at the wrong part of the code. The part you're showing in the screenshot is actually implemented with a btn--bare, so you'd use `--px-btn-bare-color` `--px-btn-bare-color--hover` and `--px-btn-bare-color--pressed` instead.

**Comment by austinmcdaniel** [comment]
Thanks, that worked.
